# Generated by Django 5.0.3 on 2024-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_for_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askforoffer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
